name = "new-deploy-test"
version = "0.0.1"
deployers = ["0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266", "0xca7777aB932E8F0b930dE9F0d96f4E9a2a00DdD3"]

[var.settings]
owner = "0xca7777aB932E8F0b930dE9F0d96f4E9a2a00DdD3"

[clone.MintableToken]
source = "mintable-token"
target = "new-deploy-test@MintableToken"
options.decimals = "18"
options.initialSupply = "0"
options.name = "Token"
options.owner = "<%= settings.owner %>"
options.salt = "new-salt"
