name = "new-deploy-test"
version = "0.0.1"
deployers = ["0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266", "0xca7777aB932E8F0b930dE9F0d96f4E9a2a00DdD3"]

[var.settings]
owner = "0xca7777aB932E8F0b930dE9F0d96f4E9a2a00DdD3"

[clone.OwnedGreeter]
source = "owned-greeter"
target = "new-deploy-test@owned-greeter"

[clone.MintableToken]
source = "mintable-token"
target = "new-deploy-test@MintableToken"
options.decimals = "18"
options.initialSupply = "0"
options.name = "Token"
options.owner = "<%= settings.owner %>"
options.salt = "new-salt"

[clone.trusted_multicall_forwarder]
source = "trusted-multicall-forwarder"
target = "new-deploy-test@trusted-multicall-forwarder"
options.salt = "new-salt"

[clone.Proxy]
source = "transparent-upgradable-proxy"
target = "new-deploy-test@transparent-upgradeable-proxy"
options.admin = "<%= settings.owner %>"
options.abi = "<%= JSON.stringify(imports.OwnedGreeter.contracts.Greeter.abi) %>"
options.implementation = "<%= imports.OwnedGreeter.contracts.Greeter.address %>"
depends=["clone.OwnedGreeter"]

[invoke.greet]
target = ["Proxy.Proxy"]
from = "<%= settings.owner %>"
abi = "<%= JSON.stringify(imports.OwnedGreeter.contracts.Greeter.abi) %>"
func = "greet"
args = ["<%= settings.owner %>"]
depends=["clone.Proxy"]

[invoke.mintTokens]
target = ["MintableToken.Token"]
from = "<%= settings.owner %>"
abi = "<%= JSON.stringify(imports.MintableToken.contracts.Token.abi) %>"
func = "mint"
args = ["1000", "<%= settings.owner %>"]
