name = "test-deploy"
version = "0.0.1"

[setting.owner]
defaultValue="0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.user]
defaultValue="0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.accountId]
defaultValue = "1"

[provision.greeter]
source = "greeter:2.10.0"

[invoke.greet]
target = ["greeter.Greeter"]
func = "setGreeting"
args = ["changed one more time"]

[invoke.secondGreet]
target = ["greeter.Greeter"]
func = "setGreeting"
args = ["changed one last time"]

[import.synthetix]
source = "synthetix:latest@main"

# User creates account
[invoke.createAccount]
target = ["synthetix.CoreProxy"]
from = "<%= settings.user %>"
func = "createAccount(uint128)"
args = ["<%= settings.accountId %>"]
extras.accountId.event = "AccountCreated"
extras.accountId.arg = 0