name = "test-deploy"
version = "0.0.2"

[provision.greeter]
source = "greeter:latest"

[invoke.greet]
target = ["greeter.Greeter"]
func = "setGreeting"
args = ["changed one more time"]

[invoke.secondGreet]
target = ["greeter.Greeter"]
func = "setGreeting"
args = ["changed one last time"]

[invoke.cloneGreeter]
target = ["greeter.Greeter"]
func = "doCloning"

[invoke.cloneGreeterAgain]
target = ["greeter.Greeter"]
func = "doCloning"