name = "test-deploy-package"
version = "0.0.1"

[provision.greeter]
source = "greeter:latest"
target = "greeter:latest@with-test"

[invoke.greet]
target = ["greeter.Greeter"]
func = "setGreeting"
args = ["changed one more time"]

[invoke.cloneGreeter]
target = ["greeter.Greeter"]
func = "doCloning"