name = "test-deploy"
version = "0.0.1"

[provision.greeter]
source = "greeter:2.10.0"

[invoke.greet]
target = ["greeter.Greeter"]
func = "setGreeting"
args = ["changed one more time"]

[invoke.secondGreet]
target = ["greeter.Greeter"]
func = "setGreeting"
args = ["changed one last time"]

[provision.synthetix]
source = "synthetix:latest"
owner = "<%= settings.owner %>"

[invoke.createPool]
target = ["synthetix.CoreProxy"]
from = "<%= settings.user %>"
func = "createPool"
args = [
    "1",
    "<%= settings.owner %>"
]