name = "test-deploy-package"
version = "0.0.1"
deployers = ["0x766b80B3938f409532726c6b8cbefBf571AA8aC8","0x798578C14c54f415ecf3927AF3db0afd4aFb59cf"]

[provision.greeter]
source = "greeter:2.10.0"
target = "greeter:2.10.0@with-test"
options.salt = "some-value-2"

[invoke.greet]
target = ["greeter.Greeter"]
# have a txn that has to come from the gnosis safe.
from = "0x766b80B3938f409532726c6b8cbefBf571AA8aC8"
func = "setGreeting"
args = ["to verify upgrade from it"]

[invoke.secondGreet]
target = ["greeter.Greeter"]
func = "setGreeting"
args = ["changed one last time"]

[invoke.cloneGreeter]
target = ["greeter.Greeter"]
func = "doCloning"

[invoke.cloneGreeterAgain]
target = ["greeter.Greeter"]
func = "doCloning"
