name = "test-deploy-package"
version = "0.0.1"
deployers = ["0xca7777aB932E8F0b930dE9F0d96f4E9a2a00DdD3", "0x14E0f81A0c60A35D0424c0b08aF3146d16eB98F6"]
preset = "regre"

[provision.greeter]
source = "greeter:2.10.0"
target = "greeter:2.10.0@with-test"
options.salt = "some-value-2"

[invoke.greet]
target = ["greeter.Greeter"]
# have a txn that has to come from the gnosis safe.
from = "0x14E0f81A0c60A35D0424c0b08aF3146d16eB98F6"
func = "setGreeting"
args = ["to verify upgrade from it"]

[invoke.secondGreet]
target = ["greeter.Greeter"]
func = "setGreeting"
args = ["change another time"]

[invoke.cloneGreeter]
target = ["greeter.Greeter"]
func = "doCloning"

[invoke.cloneGreeterAgain]
target = ["greeter.Greeter"]
func = "doCloning"
