name = "usecannon-gitops-test"
version = "0.0.1"
preset = "regre"

[var.settings]
owner = "0x7f28058F0b989430C7397782F797e300CDc10042"

[clone.greeter]
source = "greeter:2.10.0"
target = "usecannon-gitops-test:0.0.1@regre-greeter"

[invoke.greet]
target = ["greeter.Greeter"]
func = "setGreeting"
args = ["changed one more time"]

[invoke.secondGreet]
from = "<%= settings.owner %>"
target = ["greeter.Greeter"]
func = "setGreeting"
args = ["changed one last time"]
